#Makefile to make a Peanut butter and Jelly Sandwich
#slanka for DO at Home exercises
#make file that desribes the steps invovled in PBJ sandwich

all:
	 @echo ""
	 @echo "  1.  Heating a pan upto 350 degrees F or 175 degrees C for sometime."
	 @echo ""
	 @echo "  2.  While the pan is heating, Spreading butter evenly on one side of both the slices of the Sandwich bread."
	 @echo ""
	 @echo "  3.  On the unbuttered side of the slices spreading peanut butter on one slice and Grape Jelly on the other."
	 @echo ""
	 @echo "  4.  Adding Greek Yogurt and cinnamon powder or blueberries on wach slice"
	 @echo ""
	 @echo "  5.  Cook until brown on the buttered side of slices flipping them over timely"
	 @echo ""
	 @echo "  6.  Making sure both sides of the sandwich are evenly cooked."
	 @echo ""
	 @echo "  7.  Enjoy the Sandwich!";
	 @echo ""


1: 
	@echo ""
	@echo "  Heating a pan upto 350 degrees F or 175 degrees C for sometime."
	@echo ""
2: 
	@echo ""
	@echo "  While the pan is heating, Spreading butter evenly on one side of both the slices of the Sandwich bread."
	@echo ""
3: 
	@echo ""
	@echo "  On the unbuttered side of the slices spreading peanut butter on one slice and Grape Jelly on the other."
	@echo ""
4: 	
	@echo ""
	@echo "  Adding Greek Yogurt and cinnamon powder or blueberries on wach slice"
	@echo ""
5:  
	@echo " "
	@echo "  Cook until brown on the buttered side of slices flipping them over timely"
	@echo ""
6: 
	@echo ""
	@echo "  Making sure both sides of the sandwich are evenly cooked."
	@echo ""
7: 
	@echo ""
	@echo "  Enjoy the Sandwich!"
	@echo ""
